#if !canImport(ObjectiveC)
import XCTest

extension DecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecoderTests = [
        ("testAsyncDecode", testAsyncDecode),
        ("testAsyncDecodeSpeed", testAsyncDecodeSpeed),
        ("testSyncDecode", testSyncDecode),
        ("testSyncDecodeSpeed", testSyncDecodeSpeed),
    ]
}

extension EncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncoderTests = [
        ("testAsyncEncode", testAsyncEncode),
        ("testEscapingDelimiters", testEscapingDelimiters),
        ("testMeasureAsyncEncode", testMeasureAsyncEncode),
        ("testMeasureSyncEncode", testMeasureSyncEncode),
        ("testSyncEncode", testSyncEncode),
    ]
}

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testChunkedParsing", testChunkedParsing),
        ("testMeasureChunkedParse", testMeasureChunkedParse),
        ("testMeasureFullParse", testMeasureFullParse),
        ("testParserInit", testParserInit),
        ("testParserParse", testParserParse),
    ]
}

extension SerializerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SerializerTests = [
        ("testChunkedSerialize", testChunkedSerialize),
        ("testEscapedDelimiter", testEscapedDelimiter),
        ("testMeasuerSyncSerializer", testMeasuerSyncSerializer),
        ("testMeasureChunkedSerialize", testMeasureChunkedSerialize),
        ("testSyncSerialize", testSyncSerialize),
    ]
}

extension StressTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StressTests = [
        ("testMeasureAsyncDecoding", testMeasureAsyncDecoding),
        ("testMeasureAsyncEncoding", testMeasureAsyncEncoding),
        ("testMeasureAsyncParsing", testMeasureAsyncParsing),
        ("testMeasureAsyncSerialize", testMeasureAsyncSerialize),
        ("testMeasureSyncDecoding", testMeasureSyncDecoding),
        ("testMeasureSyncEncoding", testMeasureSyncEncoding),
        ("testMeasureSyncParsing", testMeasureSyncParsing),
        ("testMeasureSyncSerialize", testMeasureSyncSerialize),
    ]
}

extension UtilityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilityTests = [
        ("testBytesToDouble", testBytesToDouble),
        ("testBytesToFloat", testBytesToFloat),
        ("testBytesToInt", testBytesToInt),
        ("testMeasureBytesToDouble", testMeasureBytesToDouble),
        ("testMeasureBytesToFloat", testMeasureBytesToFloat),
        ("testMeasureBytesToInt", testMeasureBytesToInt),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DecoderTests.__allTests__DecoderTests),
        testCase(EncoderTests.__allTests__EncoderTests),
        testCase(ParserTests.__allTests__ParserTests),
        testCase(SerializerTests.__allTests__SerializerTests),
        testCase(StressTests.__allTests__StressTests),
        testCase(UtilityTests.__allTests__UtilityTests),
    ]
}
#endif
